PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_12_16_195002_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2025_12_17_160405_create_annee_scolaires_table',1);
INSERT INTO migrations VALUES(6,'2025_12_17_160710_create_parents_tuteurs_table',2);
INSERT INTO migrations VALUES(7,'2025_12_17_160745_create_eleves_table',2);
INSERT INTO migrations VALUES(8,'2025_12_17_161025_create_relations_eleve_tuteur_table',2);
INSERT INTO migrations VALUES(9,'2025_12_17_161124_create_niveaux_scolaires_table',2);
INSERT INTO migrations VALUES(10,'2025_12_17_161347_create_cycles_table',2);
INSERT INTO migrations VALUES(11,'2025_12_17_161527_create_classes_table',2);
INSERT INTO migrations VALUES(12,'2025_12_17_161620_create_affectations__classes_table',2);
INSERT INTO migrations VALUES(13,'2025_12_17_161834_create_inscriptions_table',2);
INSERT INTO migrations VALUES(14,'2025_12_17_162114_create_documents_eleves_table',2);
INSERT INTO migrations VALUES(15,'2025_12_17_162333_create_fiches_inscription_table',2);
INSERT INTO migrations VALUES(16,'2025_12_17_162439_create_cartes_scolarite_table',2);
INSERT INTO migrations VALUES(17,'2025_12_17_162557_create_notifications_table',2);
INSERT INTO migrations VALUES(18,'2025_12_17_162820_create_preferences_notifications_table',2);
INSERT INTO migrations VALUES(19,'2025_12_17_162948_create_logs_activite_table',2);
INSERT INTO migrations VALUES(20,'2025_12_17_163308_create_cours_table',2);
INSERT INTO migrations VALUES(21,'2025_12_17_163441_create_presence_table',2);
INSERT INTO migrations VALUES(22,'2025_12_17_163518_create_requetes_table',2);
INSERT INTO migrations VALUES(23,'2025_12_17_163606_create_permission_table',2);
INSERT INTO migrations VALUES(24,'2025_12_17_164217_create_responsables_table',2);
INSERT INTO migrations VALUES(25,'2025_12_17_164346_create_enseignants_table',2);
INSERT INTO migrations VALUES(26,'2025_12_17_165001_create_series_table',2);
INSERT INTO migrations VALUES(27,'2025_12_17_165335_create_matieres_table',2);
INSERT INTO migrations VALUES(28,'2025_12_17_165427_create_coefficients_table',2);
INSERT INTO migrations VALUES(29,'2025_12_17_165520_create_semestres_table',2);
INSERT INTO migrations VALUES(30,'2025_12_17_165606_create_notes_table',2);
INSERT INTO migrations VALUES(31,'2025_12_17_165700_create_evaluations_table',2);
INSERT INTO migrations VALUES(32,'2025_12_17_165746_create_bulletins_table',2);
INSERT INTO migrations VALUES(33,'2025_12_17_165955_create_statistiques_table',3);
INSERT INTO migrations VALUES(34,'2025_12_17_170347_add_foreign_keys_to_eleves_table',3);
INSERT INTO migrations VALUES(35,'2025_12_17_171738_create_frais_type_table',3);
INSERT INTO migrations VALUES(36,'2025_12_17_172029_create_tranche_paiement_table',3);
INSERT INTO migrations VALUES(37,'2025_12_17_172129_create_paiement_table',3);
INSERT INTO migrations VALUES(38,'2025_12_17_172230_create_remboursement_table',3);
INSERT INTO migrations VALUES(39,'2025_12_17_172325_create_statistique_financiere_table',3);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "annee_scolaires_table" ("id" integer primary key autoincrement not null, "annee" varchar not null, "date_debut" date, "date_fin" date, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "parents_tuteurs" ("id" integer primary key autoincrement not null, "user_id" integer, "nom" varchar not null, "prenom" varchar not null, "telephone" varchar, "email" varchar, "adresse" varchar, "profession" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "relations_eleve_tuteur" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "tuteur_id" integer not null, "relation_type" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("tuteur_id") references "parents_tuteurs"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "niveaux_scolaires" ("id" integer primary key autoincrement not null, "nom" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "cycles" ("id" integer primary key autoincrement not null, "nom" varchar not null, "niveau_id" integer not null, "description" text, "created_at" datetime, "updated_at" datetime, foreign key("niveau_id") references "niveaux_scolaires"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "classes" ("id" integer primary key autoincrement not null, "nom" varchar not null, "niveau_id" integer not null, "description" text, "annee_scolaire" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("niveau_id") references "niveaux_scolaires"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "affectations_classes" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "classe_id" integer not null, "date_affectation" date not null default CURRENT_DATE, "statut" varchar not null default 'affecte', "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("classe_id") references "classes"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "inscriptions" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "annee_scolaire_id" integer not null, "date_inscription" date not null default CURRENT_DATE, "statut" varchar not null default 'inscrit', "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("annee_scolaire_id") references "annee_scolaires"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "documents_eleves" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "type" varchar not null, "url" varchar not null, "upload_date" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "fiches_inscription" ("id" integer primary key autoincrement not null, "inscription_id" integer not null, "details" text, "url" varchar, "created_at" datetime, "updated_at" datetime, foreign key("inscription_id") references "inscriptions"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "cartes_scolarite" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "numero_carte" varchar not null, "date_emission" date not null default CURRENT_DATE, "date_expiration" date, "statut" varchar not null default 'valide', "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "notifications" ("id" integer primary key autoincrement not null, "type" varchar not null, "message" text not null, "destinataire_id" integer not null, "date_envoi" datetime not null default CURRENT_TIMESTAMP, "lu" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("destinataire_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "preferences_notifications" ("id" integer primary key autoincrement not null, "user_id" integer not null, "notification_type" varchar not null, "via_email" tinyint(1) not null default '1', "via_WhatsApp" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "logs_activite" ("id" integer primary key autoincrement not null, "user_id" integer, "action" varchar not null, "details" text, "timestamp" datetime not null default CURRENT_TIMESTAMP, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "cours" ("id" integer primary key autoincrement not null, "classe_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("classe_id") references "classes"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "presence" ("id" integer primary key autoincrement not null, "classe_id" integer, "cours_id" integer, "eleve_id" integer, "date" date not null, "heure" varchar not null, "present" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("classe_id") references "classes"("id") on delete set null, foreign key("cours_id") references "cours"("id") on delete set null, foreign key("eleve_id") references "eleves"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "requetes" ("id" integer primary key autoincrement not null, "parent_id" integer, "objet" text not null, "desc" text, "created_at" datetime, "updated_at" datetime, foreign key("parent_id") references "parents_tuteurs"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "permission" ("id" integer primary key autoincrement not null, "user_id" integer, "objet" text not null, "desc" text, "statut" varchar not null default 'en_attente', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "responsables" ("id" integer primary key autoincrement not null, "user_id" integer not null, "fonction" varchar not null default 'Administrateur', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "enseignants" ("id" integer primary key autoincrement not null, "user_id" integer not null, "matiere" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "series" ("id" integer primary key autoincrement not null, "nom" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "matieres" ("id" integer primary key autoincrement not null, "nom" varchar not null, "coefficient" integer not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "coefficients" ("id" integer primary key autoincrement not null, "matiere_id" integer not null, "valeur" integer not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("matiere_id") references "matieres"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "semestres" ("id" integer primary key autoincrement not null, "nom" varchar not null, "date_debut" date, "date_fin" date, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "notes" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "matiere_id" integer not null, "semestre_id" integer not null, "valeur" numeric not null, "date_note" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("matiere_id") references "matieres"("id") on delete cascade, foreign key("semestre_id") references "semestres"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "evaluations" ("id" integer primary key autoincrement not null, "matiere_id" integer not null, "eleve_id" integer not null, "semestre_id" integer not null, "valeur" numeric not null, "date_eval" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime, foreign key("matiere_id") references "matieres"("id") on delete cascade, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("semestre_id") references "semestres"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "bulletins" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "annee_scolaire" varchar not null, "moyenne" numeric, "rang" integer, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "statistiques" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "moyenne" numeric, "rang" integer, "annee_scolaire" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "eleves" ("id" integer primary key autoincrement not null, "user_id" integer not null, "classe_id" integer not null, "created_at" datetime, "updated_at" datetime, "serie_id" integer not null, foreign key("classe_id") references classes("id") on delete cascade on update no action, foreign key("user_id") references users("id") on delete cascade on update no action, foreign key("serie_id") references "series"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "frais_type" ("id" integer primary key autoincrement not null, "nom" varchar not null, "description" text, "montant_defaut" numeric not null default '0', "est_obligatoire" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "tranche_paiement" ("id" integer primary key autoincrement not null, "frais_type_id" integer not null, "nom_tranche" varchar not null, "pourcentage_du_total" numeric not null default '0', "date_limite" date, "created_at" datetime, "updated_at" datetime, foreign key("frais_type_id") references "frais_type"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "paiement" ("id" integer primary key autoincrement not null, "eleve_id" integer not null, "tranche_id" integer not null, "montant_paye" numeric not null, "mode_paiement" varchar not null default 'cash', "reference_paiement" varchar, "statut" varchar not null default 'en attente', "date_paiement" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime, foreign key("eleve_id") references "eleves"("id") on delete cascade, foreign key("tranche_id") references "tranche_paiement"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "remboursement" ("id" integer primary key autoincrement not null, "paiement_id" integer not null, "montant_rembourse" numeric not null, "motif" text, "statut" varchar not null default 'initié', "date_remboursement" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime, foreign key("paiement_id") references "paiement"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "statistique_financiere" ("id" integer primary key autoincrement not null, "annee_scolaire" varchar not null, "total_recettes" numeric not null default '0', "total_remboursements" numeric not null default '0', "nombre_eleves_payants" integer not null default '0', "date_generation" date not null default CURRENT_DATE, "created_at" datetime, "updated_at" datetime);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',39);
INSERT INTO sqlite_sequence VALUES('eleves',0);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
CREATE INDEX "parents_tuteurs_user_id_index" on "parents_tuteurs" ("user_id");
CREATE UNIQUE INDEX "relations_eleve_tuteur_eleve_id_tuteur_id_unique" on "relations_eleve_tuteur" ("eleve_id", "tuteur_id");
CREATE INDEX "relations_eleve_tuteur_eleve_id_index" on "relations_eleve_tuteur" ("eleve_id");
CREATE INDEX "relations_eleve_tuteur_tuteur_id_index" on "relations_eleve_tuteur" ("tuteur_id");
CREATE UNIQUE INDEX "niveaux_scolaires_nom_unique" on "niveaux_scolaires" ("nom");
CREATE UNIQUE INDEX "cycles_nom_niveau_id_unique" on "cycles" ("nom", "niveau_id");
CREATE UNIQUE INDEX "classes_nom_niveau_id_unique" on "classes" ("nom", "niveau_id");
CREATE INDEX "classes_annee_scolaire_index" on "classes" ("annee_scolaire");
CREATE UNIQUE INDEX "affectations_classes_eleve_id_classe_id_unique" on "affectations_classes" ("eleve_id", "classe_id");
CREATE INDEX "affectations_classes_eleve_id_index" on "affectations_classes" ("eleve_id");
CREATE INDEX "affectations_classes_classe_id_index" on "affectations_classes" ("classe_id");
CREATE UNIQUE INDEX "inscriptions_eleve_id_annee_scolaire_id_unique" on "inscriptions" ("eleve_id", "annee_scolaire_id");
CREATE INDEX "inscriptions_eleve_id_index" on "inscriptions" ("eleve_id");
CREATE INDEX "inscriptions_annee_scolaire_id_index" on "inscriptions" ("annee_scolaire_id");
CREATE INDEX "documents_eleves_eleve_id_index" on "documents_eleves" ("eleve_id");
CREATE INDEX "fiches_inscription_inscription_id_index" on "fiches_inscription" ("inscription_id");
CREATE INDEX "cartes_scolarite_eleve_id_index" on "cartes_scolarite" ("eleve_id");
CREATE UNIQUE INDEX "cartes_scolarite_numero_carte_unique" on "cartes_scolarite" ("numero_carte");
CREATE INDEX "notifications_destinataire_id_index" on "notifications" ("destinataire_id");
CREATE UNIQUE INDEX "preferences_notifications_user_id_notification_type_unique" on "preferences_notifications" ("user_id", "notification_type");
CREATE INDEX "preferences_notifications_user_id_index" on "preferences_notifications" ("user_id");
CREATE INDEX "logs_activite_user_id_index" on "logs_activite" ("user_id");
CREATE INDEX "logs_activite_timestamp_index" on "logs_activite" ("timestamp");
CREATE INDEX "cours_classe_id_index" on "cours" ("classe_id");
CREATE INDEX "presence_classe_id_index" on "presence" ("classe_id");
CREATE INDEX "presence_cours_id_index" on "presence" ("cours_id");
CREATE INDEX "presence_eleve_id_index" on "presence" ("eleve_id");
CREATE INDEX "presence_date_index" on "presence" ("date");
CREATE INDEX "requetes_parent_id_index" on "requetes" ("parent_id");
CREATE INDEX "permission_user_id_index" on "permission" ("user_id");
CREATE INDEX "responsables_user_id_index" on "responsables" ("user_id");
CREATE UNIQUE INDEX "responsables_user_id_unique" on "responsables" ("user_id");
CREATE INDEX "enseignants_user_id_index" on "enseignants" ("user_id");
CREATE UNIQUE INDEX "enseignants_user_id_unique" on "enseignants" ("user_id");
CREATE INDEX "coefficients_matiere_id_index" on "coefficients" ("matiere_id");
CREATE INDEX "notes_eleve_id_index" on "notes" ("eleve_id");
CREATE INDEX "notes_matiere_id_index" on "notes" ("matiere_id");
CREATE INDEX "notes_semestre_id_index" on "notes" ("semestre_id");
CREATE INDEX "notes_date_note_index" on "notes" ("date_note");
CREATE INDEX "evaluations_matiere_id_index" on "evaluations" ("matiere_id");
CREATE INDEX "evaluations_eleve_id_index" on "evaluations" ("eleve_id");
CREATE INDEX "evaluations_semestre_id_index" on "evaluations" ("semestre_id");
CREATE INDEX "evaluations_date_eval_index" on "evaluations" ("date_eval");
CREATE INDEX "bulletins_eleve_id_index" on "bulletins" ("eleve_id");
CREATE INDEX "bulletins_annee_scolaire_index" on "bulletins" ("annee_scolaire");
CREATE INDEX "statistiques_eleve_id_index" on "statistiques" ("eleve_id");
CREATE INDEX "statistiques_annee_scolaire_index" on "statistiques" ("annee_scolaire");
CREATE INDEX "eleves_classe_id_index" on "eleves" ("classe_id");
CREATE INDEX "eleves_user_id_index" on "eleves" ("user_id");
CREATE UNIQUE INDEX "eleves_user_id_unique" on "eleves" ("user_id");
CREATE INDEX "frais_type_nom_index" on "frais_type" ("nom");
CREATE INDEX "tranche_paiement_frais_type_id_index" on "tranche_paiement" ("frais_type_id");
CREATE INDEX "paiement_eleve_id_index" on "paiement" ("eleve_id");
CREATE INDEX "paiement_tranche_id_index" on "paiement" ("tranche_id");
CREATE INDEX "paiement_statut_index" on "paiement" ("statut");
CREATE INDEX "paiement_date_paiement_index" on "paiement" ("date_paiement");
CREATE INDEX "remboursement_paiement_id_index" on "remboursement" ("paiement_id");
CREATE INDEX "remboursement_statut_index" on "remboursement" ("statut");
CREATE INDEX "statistique_financiere_annee_scolaire_index" on "statistique_financiere" ("annee_scolaire");
COMMIT;
