<?php

namespace App\Http\Controllers;

use App\Models\Eleve;
use App\Models\Notification;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\DB;

class ScolariteController extends Controller
{
    /**
     * Generate PDF ID card for a student.
     */
    public function generateIDCard($eleveId)
    {
        $eleve = Eleve::with(['user', 'classe.niveauScolaire'])->findOrFail($eleveId);
        
        $data = [
            'eleve' => $eleve,
            'school_name' => \App\Models\Setting::getValue('schoolName', 'School-HUB Academy'),
            'academic_year' => \App\Models\Setting::getValue('academicYear', '2025-2026'),
            'date' => now()->format('d/m/Y')
        ];

        $pdf = Pdf::loadView('pdfs.id_card', $data)->setPaper([0, 0, 240, 150], 'landscape');
        
        return $pdf->download("Carte_{$eleve->matricule}.pdf");
    }

    /**
     * Get history of all documents generated by the system.
     */
    public function getDocumentsHistory()
    {
        // For now, we aggregate data from multiple tables to simulate a document history
        // Real archival would use a 'documents' table
        
        $payments = DB::table('paiement')
            ->join('eleves', 'paiement.eleve_id', '=', 'eleves.id')
            ->join('users', 'eleves.user_id', '=', 'users.id')
            ->join('classes', 'eleves.classe_id', '=', 'classes.id')
            ->select(
                'paiement.id',
                DB::raw("'Reçu' as type"),
                DB::raw("CONCAT('Paiement ', paiement.reference_paiement) as name"),
                DB::raw("CONCAT(users.nom, ' ', users.prenom) as student"),
                'classes.nom as class',
                'paiement.date_paiement as date',
                DB::raw("'Signé' as status")
            );

        $bulletins = DB::table('bulletins')
            ->join('eleves', 'bulletins.eleve_id', '=', 'eleves.id')
            ->join('users', 'eleves.user_id', '=', 'users.id')
            ->join('classes', 'eleves.classe_id', '=', 'classes.id')
            ->select(
                'bulletins.id',
                DB::raw("'Bulletin' as type"),
                DB::raw("'Bulletin Semestriel' as name"),
                DB::raw("CONCAT(users.nom, ' ', users.prenom) as student"),
                'classes.nom as class',
                'bulletins.created_at as date',
                DB::raw("'Généré' as status")
            );

        $documents = $payments->union($bulletins)
            ->orderBy('date', 'desc')
            ->limit(100)
            ->get();

        return response()->json($documents);
    }
}
